### ISSUE TITLE
Can't connect with TurboVNC from Ubuntu 16.04 (javax.net.ssl.SSLHandshakeException)

### ISSUE THREAD

**Issue by PolarNick239** [agisoft-llc/cloud-scripts#8]
Hi, I executed scripts following instructions with Ubuntu 16.04 Server on aws g3 instance and Ubuntu 16.04 Desktop on local PC.

And after executing command ```/opt/TurboVNC/bin/vncviewer ${ip}:5901``` I encounter:

```
libjawt.so path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
CConn: connected to host 54.78.16.121 port 5901
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
com.turbovnc.rdr.SystemException: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.turbovnc.rfb.CSecurityTLS.processMsg(CSecurityTLS.java:124)
	at com.turbovnc.rfb.CSecurityTLS.processMsg(CSecurityTLS.java:87)
	at com.turbovnc.rfb.CSecurityStack.processMsg(CSecurityStack.java:39)
	at com.turbovnc.rfb.CSecurityVeNCrypt.processMsg(CSecurityVeNCrypt.java:179)
	at com.turbovnc.rfb.CSecurityTight.processMsg(CSecurityTight.java:56)
	at com.turbovnc.rfb.CConnection.processSecurityMsg(CConnection.java:213)
	at com.turbovnc.rfb.CConnection.processMsg(CConnection.java:62)
	at com.turbovnc.vncviewer.VncViewer.run(VncViewer.java:838)
	at java.lang.Thread.run(Thread.java:748)
```

Can you help please?

**Comment by PolarNick239** [comment]
Hi!

Yes, I also encountered this. Seems that this can be fixed via java security config (see https://stackoverflow.com/a/57273918 ).

I also use Ubuntu 16.04 and for me security config was located at ```/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security``` and commenting out two consequent lines with jdk.tls.disabledAlgorithms ... helped. Note that first line of TurboVNC output provided by you can help to locate JRE directory.

**Comment by PolarNick239** [comment]
Thanks! Works like a charm!

**Comment by PgLoLo** [comment]
Finally, some high quality fixes. Thank you very much!
